### ISSUE TITLE
Proxy Addon

### ISSUE THREAD

**Issue by devpanda0** [reformcloudproject/reformcloud#12]

**Comment by derklaro** [comment]
Test version created with ac5b8ec4eacc03191dafcbaba963cf94829a9fac and 412b7a19990577880fe204197ac0d092f432a2a5

**Comment by derklaro** [comment]
Features added with ebf99f4a2e5f83cf5e6c3f89e8746f0edc10027c and 57fa5e8d71d81076b3234352c6fa3a2273138ad6
