### ISSUE TITLE
Git commit messages

### ISSUE THREAD

**Issue by Jevzo** [reformcloudproject/reformcloud#121]
### Git Commit Messages

I will link you a little guid where you can look how to write good Git Commit Messages. 
Things like "Added" "Fixed" are not good for Commit Messages.

Link: [Git Commit Messages](https://beams.io/posts/git-commit/)
Normal Link: https://beams.io/posts/git-commit/

Happy Hacking and Happy Learning :)

Cheers,
Jerry

**Comment by ByteExceptionM** [comment]
Hey, I think as long as you know what we mean, it's enough - but thanks anyway :) I will have a look at the page :)

**Comment by derklaro** [comment]
Hey @Jeerrryyyy ,

thank you to mention this. In my personal opinion it's not the worst thing which could happen, but we'll think about it and change it in the future! 👍 

_Klaro

**Comment by derklaro** [comment]
If you see any commit messages, which should be better, just mention them here :)

**Comment by derklaro** [comment]
Due to no further replies we decided to close this issue

**Comment by Jevzo** [comment]
Sure. Just wanted you to read the little article about commit messages. 

Cheers
