### ISSUE TITLE
getAllRegisteredServers

### ISSUE THREAD

**Issue by devpanda0** [reformcloudproject/reformcloud#20]
getAllRegisteredServers in der Spigot API gibt noch null zurück

**Comment by derklaro** [comment]
https://github.com/reformcloudproject/reformcloud/blob/3a026f14da47db6cf9eb3829212ee97896e10318/reformcloud-global/reformcloud-api/reformcloud-api-spigot/src/main/java/systems/reformcloud/ReformCloudAPISpigot.java#L334-L337

gibt nicht mehr null zurück
